-- MySQL Script generated by MySQL Workbench
-- Sat Feb  3 14:05:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`submissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`submissions` (
  `submissionId` INT NOT NULL,
  `submissionDate` DATE NULL,
  `institution` VARCHAR(45) NOT NULL,
  `major` VARCHAR(45) NOT NULL,
  `degree` VARCHAR(45) NULL,
  `sem` VARCHAR(3) NULL,
  `notif_result` VARCHAR(20) NOT NULL,
  `notif_method` VARCHAR(20) NULL,
  `notif_date` DATE NULL,
  `studentType` VARCHAR(45) NULL,
  `gpa` DECIMAL(5,2) NULL,
  `gre_v` INT NULL,
  `gre_q` INT NULL,
  `gre_w` DECIMAL(3,2) NULL,
  `gre_subject` VARCHAR(45) NULL,
  `notes` VARCHAR(100) NULL,
  PRIMARY KEY (`submissionId`),
  UNIQUE INDEX `submissionId_UNIQUE` (`submissionId` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
